/var/log/<APP_SLUG>.log	<APP_USER>:<APP_GROUP>	640  7	2048	*	JC	<APP_ROOT>/run/<APP_SERVICE_NAME>.pid
/var/log/<APP_SLUG>-backup.log	root:wheel	640  7	512	*	JC
/var/log/<APP_SLUG>-maintenance.log	root:wheel	640  7	256	*	JC
